// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-05 16:30:30
// =================================================================================

package entity

// FreezingPointsRecord is the golang structure for table freezing_points_record.
type FreezingPointsRecord struct {
	Id             uint64 `json:"id"             description:"记录ID"`
	BasicUid       int64  `json:"basicUid"       description:"全局用户ID"`
	FromType       int    `json:"fromType"       description:"来源类型 0）下单；1）下级消费奖励；2）退单申请；3）下级退单申请"`
	FromBasicUid   int64  `json:"fromBasicUid"   description:"下级全局用户ID"`
	OrderId        int64  `json:"orderId"        description:"所属订单ID"`
	IncomeRecordId int    `json:"incomeRecordId" description:"支付记录ID"`
	RefundId       int    `json:"refundId"       description:"退款记录ID"`
	Integral       int    `json:"integral"       description:"冻结积分数量"`
	Status         int    `json:"status"         description:"状态 0）已冻结 1）解除冻结 2）已失效"`
	Content        string `json:"content"        description:"操作详情"`
	IsDelete       int    `json:"isDelete"       description:"是否删除：1是，0否"`
	CreatedAt      int64  `json:"createdAt"      description:"创建时间"`
	UpdatedAt      int64  `json:"updatedAt"      description:"最近更新时间"`
}
