// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-05 16:30:30
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// FreezingPointsRecord is the golang structure of table he_freezing_points_record for DAO operations like Where/Data.
type FreezingPointsRecord struct {
	g.Meta         `orm:"table:he_freezing_points_record, do:true"`
	Id             interface{} // 记录ID
	BasicUid       interface{} // 全局用户ID
	FromType       interface{} // 来源类型 0）下单；1）下级消费奖励；2）退单申请；3）下级退单申请
	FromBasicUid   interface{} // 下级全局用户ID
	OrderId        interface{} // 所属订单ID
	IncomeRecordId interface{} // 支付记录ID
	RefundId       interface{} // 退款记录ID
	Integral       interface{} // 冻结积分数量
	Status         interface{} // 状态 0）已冻结 1）解除冻结 2）已失效
	Content        interface{} // 操作详情
	IsDelete       interface{} // 是否删除：1是，0否
	CreatedAt      interface{} // 创建时间
	UpdatedAt      interface{} // 最近更新时间
}
