// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/oncall/service/internal/dao/internal"
)

// freezingPointsRecordDao is the data access object for table he_freezing_points_record.
// You can define custom methods on it to extend its functionality as you wish.
type freezingPointsRecordDao struct {
	*internal.FreezingPointsRecordDao
}

var (
	// FreezingPointsRecord is globally public accessible object for table he_freezing_points_record operations.
	FreezingPointsRecord = freezingPointsRecordDao{
		internal.NewFreezingPointsRecordDao(),
	}
)

// Fill with you ideas below.
